language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - pnpm build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: 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
  keep_history: true
  on:
    branch: master